"""Persistent paper/collection question answering and research contracts."""

from passagen.assistant.errors import (
    AnswerValidationError,
    AssistantError,
    AssistantNotFoundError,
    CitationValidationError,
    ContextPlanError,
    InsufficientEvidenceError,
    ProviderCallError,
    ScopeError,
    StaleSourceError,
)
from passagen.assistant.models import AssistantTurn, ConversationDetail, TurnSubmission
from passagen.assistant.schemas import (
    AnswerClaim,
    AnswerKind,
    ArtifactRef,
    Citation,
    CitationArtifactKind,
    CollectionSourceSnapshot,
    ContextPlan,
    ContextSource,
    Conversation,
    ConversationScope,
    GenerationRunKind,
    GenerationRunStatus,
    GenerationStage,
    Message,
    MessageRole,
    MessageStatus,
    PaperSourceSnapshot,
    QaRecord,
    QuestionIntent,
    SourceSnapshot,
    StructuredAnswer,
    source_fingerprint,
)
from passagen.assistant.service import ConversationService
from passagen.assistant.versions import (
    ANSWER_SCHEMA_VERSION,
    CONTEXT_BUILDER_VERSION,
    CONTEXT_PLAN_VERSION,
    QA_PROMPT_VERSION,
    RETRIEVAL_VERSION,
    SNAPSHOT_SCHEMA_VERSION,
)

__all__ = [
    "ANSWER_SCHEMA_VERSION",
    "CONTEXT_BUILDER_VERSION",
    "CONTEXT_PLAN_VERSION",
    "QA_PROMPT_VERSION",
    "RETRIEVAL_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "AnswerClaim",
    "AnswerKind",
    "AnswerValidationError",
    "ArtifactRef",
    "AssistantError",
    "AssistantNotFoundError",
    "AssistantTurn",
    "Citation",
    "CitationArtifactKind",
    "CitationValidationError",
    "CollectionSourceSnapshot",
    "ContextPlan",
    "ContextPlanError",
    "ContextSource",
    "Conversation",
    "ConversationDetail",
    "ConversationScope",
    "ConversationService",
    "GenerationRunKind",
    "GenerationRunStatus",
    "GenerationStage",
    "InsufficientEvidenceError",
    "Message",
    "MessageRole",
    "MessageStatus",
    "PaperSourceSnapshot",
    "ProviderCallError",
    "QaRecord",
    "QuestionIntent",
    "ScopeError",
    "SourceSnapshot",
    "StaleSourceError",
    "StructuredAnswer",
    "TurnSubmission",
    "source_fingerprint",
]
